version: 2.27.1

services:
  next-app:
    container_name: next-app
    environment:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app/next-app:cached
    restart: always
    ports:
      - 3000:3000
    command: ["bun", "run", "start"]
