version: "3.9"

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app/next-app:cached
    restart: always
    ports:
      - 3000:3000
    command: ["bun", "run", "start"]
